name: DebugBuild

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  #リポジトリのルートディレクトリを基点としたソリューションのファイルパス
  SOLUTION_FILE_PATH: Engine/CitrusJunosEngine.sln
  #VSの構成(Debug/Release)
  CONFIGURATION: Debug

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Server-Media-Foundation
      shell: powershell
      run: |
        Install-WindowsFeature Server-Media-Foundation

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architexture: x64

    - name: Build
      run: |
        msbuild ${{env.SOLUTION_FILE_PATH}} /p:Platform=x64,Configuration=${{env.CONFIGURATION}}